Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -38,8 +38,8 @@ env:
   EXAMPLES_RELEASE_ENVIRONMENT_NAME: release_environment
   EXAMPLES_RELEASE_MANAGER_BRANCH: dev-release-mgmt
 
-  # Needs 'repo' scope for org or anax
-  OPENHORIZON_ORGANIZATION_RELEASE_TOKEN: ${{ secrets.OPENHORIZON_ORGANIZATION_RELEASE_TOKEN }}
+  # Needs 'repo' scope for org or anax,examples
+  OPENHORIZON_RELEASE_MANAGER_TOKEN: ${{ secrets.OPENHORIZON_RELEASE_MANAGER_TOKEN }}
 
 jobs:
 
@@ -49,14 +49,53 @@ jobs:
     environment: release_environment
 
     steps:
+      - name: Check if Open Horizon Release Already Exists
+        run: |
+          RELEASE_STATUS=$(
+            curl -L \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
+              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+              'https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ env.OPENHORIZON_RELEASE_VERSION }}' \
+              | jq -r '.html_url')
+          
+          sleep 10
+
+          if [[ RELEASE_STATUS != 'null' ]]; then
+            echo "::error::Attempted to create a release for a version of Open Horizon that already has a release page, see $RELEASE_STATUS"
+            echo "::error::Release process failed, consider incrementing the Open Horizon version"
+            exit 1
+          fi
+        env:
+          OPENHORIZON_RELEASE_VERSION: ${{ vars.OPENHORIZON_RELEASE_VERSION }}
+
       - name: Trigger Anax Release Manager
         run: |
+          # Check if Anax Release Already Exists
+          RELEASE_STATUS=$(
+            curl -L \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
+              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+              'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/releases/tags/v${{ env.AGBOT_VERSION }}' \
+              | jq -r '.html_url')
+          
+          sleep 10
+
+          if [[ RELEASE_STATUS != 'null' ]]; then
+            echo "::warning::Attempted to create a release for a version of Anax that already has a release page, see $RELEASE_STATUS"
+            echo "::warning::Release process will continue without triggering a new Anax release, existing release will be linked to this Open Horizion version"
+            exit 0
+          fi
+
+          sleep 10
+
           # Get Anax Release Environment ID
           echo "::debug::Start \"Get Anax Release Environment ID\" API Call"
           ANAX_RELEASE_ENVIRONMENT_ID=$( \
             curl -L \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
               -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
               'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/environments/${{ env.ANAX_RELEASE_ENVIRONMENT_NAME }}' \
               | \
@@ -75,7 +114,7 @@ jobs:
               -w "%{http_code}\\n" \
               -X POST \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
               -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
               'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/workflows/${{ env.ANAX_RELEASE_MANAGER_FILE_NAME }}/dispatches' \
               -d '{"ref":"${{ env.ANAX_RELEASE_MANAGER_BRANCH }}","inputs":{"AGBOT_VERSION": "${{ env.AGBOT_VERSION }}","ANAX_VERSION": "${{ env.ANAX_VERSION }}","ANAX_K8S_VERSION": "${{ env.ANAX_K8S_VERSION }}","ANAX_CSS_VERSION": "${{ env.ANAX_CSS_VERSION }}","ANAX_ESS_VERSION": "${{ env.ANAX_ESS_VERSION }}"}}')
@@ -94,7 +133,7 @@ jobs:
           ANAX_RELEASE_RUN_ID=$( \
             curl -L \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
               -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
               'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs?status=waiting&event=workflow_dispatch&per_page=10&page=1' \
               | \
@@ -117,7 +156,7 @@ jobs:
               -w "%{http_code}\\n" \
               -X POST \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
               -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
               "https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs/${ANAX_RELEASE_RUN_ID}/pending_deployments" \
               -d "${ACCEPT_ANAX_RELEASE_API_CALL_DATA}")
@@ -137,7 +176,7 @@ jobs:
           ANAX_RELEASE_STATUS=$( \
             curl -L \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}"\
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}"\
               -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
               "https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs/${ANAX_RELEASE_RUN_ID}" \
               | \
@@ -163,7 +202,7 @@ jobs:
           ANAX_RELEASE_CONCLUSION=$( \
               curl -L \
                 -H "Accept: application/vnd.github+json" \
-                -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}"\
+                -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}"\
                 -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
                 "https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs/${ANAX_RELEASE_RUN_ID}" \
                 | \
@@ -186,12 +225,31 @@ jobs:
 
       - name: Trigger Examples Release Manager
         run: |
+          # Check if Examples Release Already Exists
+          RELEASE_STATUS=$(
+            curl -L \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
+              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+              'https://api.github.com/repos/${{ env.EXAMPLES_REPOSITORY_OWNER }}/${{ env.EXAMPLES_REPOSITORY_NAME }}/releases/tags/v${{ env.AGBOT_VERSION }}' \
+              | jq -r '.html_url')
+          
+          sleep 10
+
+          if [[ RELEASE_STATUS != 'null' ]]; then
+            echo "::warning::Attempted to create a release for a version of Examples that already has a release page, see $RELEASE_STATUS"
+            echo "::warning::Release process will continue without triggering a new Examples release, existing release will be linked to this Open Horizion version"
+            exit 0
+          fi
+
+          sleep 10
+
           # Get Examples Release Environment ID
           echo "::debug::Start \"Get Examples Release Environment ID\" API Call"
           EXAMPLES_RELEASE_ENVIRONMENT_ID=$( \
             curl -L \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
               -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
               'https://api.github.com/repos/${{ env.EXAMPLES_REPOSITORY_OWNER }}/${{ env.EXAMPLES_REPOSITORY_NAME }}/environments/${{ env.EXAMPLES_RELEASE_ENVIRONMENT_NAME }}' \
               | \
@@ -212,7 +270,7 @@ jobs:
               -w "%{http_code}\\n" \
               -X POST \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
               -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
               https://api.github.com/repos/${{ env.EXAMPLES_REPOSITORY_OWNER }}/${{ env.EXAMPLES_REPOSITORY_NAME }}/actions/workflows/${{ env.EXAMPLES_RELEASE_MANAGER_FILE_NAME }}/dispatches \
               -d "${TRIGGER_EXAMPLES_RELEASE_API_CALL_DATA}")
@@ -231,7 +289,7 @@ jobs:
           EXAMPLES_RELEASE_RUN_ID=$( \
             curl -L \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
               -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
               'https://api.github.com/repos/${{ env.EXAMPLES_REPOSITORY_OWNER }}/${{ env.EXAMPLES_REPOSITORY_NAME }}/actions/runs?status=waiting&event=workflow_dispatch&per_page=10&page=1' \
               | \
@@ -254,7 +312,7 @@ jobs:
               -w "%{http_code}\\n" \
               -X POST \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
               -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
               "https://api.github.com/repos/${{ env.EXAMPLES_REPOSITORY_OWNER }}/${{ env.EXAMPLES_REPOSITORY_NAME }}/actions/runs/${EXAMPLES_RELEASE_RUN_ID}/pending_deployments" \
               -d "${ACCEPT_EXAMPLES_RELEASE_API_CALL_DATA}")
@@ -274,7 +332,7 @@ jobs:
           EXAMPLES_RELEASE_STATUS=$( \
             curl -L \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}"\
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}"\
               -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
               "https://api.github.com/repos/${{ env.EXAMPLES_REPOSITORY_OWNER }}/${{ env.EXAMPLES_REPOSITORY_NAME }}/actions/runs/${EXAMPLES_RELEASE_RUN_ID}" \
               | \
@@ -300,7 +358,7 @@ jobs:
           EXAMPLES_RELEASE_CONCLUSION=$( \
               curl -L \
                 -H "Accept: application/vnd.github+json" \
-                -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}"\
+                -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}"\
                 -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
                 "https://api.github.com/repos/${{ env.EXAMPLES_REPOSITORY_OWNER }}/${{ env.EXAMPLES_REPOSITORY_NAME }}/actions/runs/${EXAMPLES_RELEASE_RUN_ID}" \
                 | \
@@ -350,7 +408,7 @@ jobs:
               -w "%{http_code}\\n" \
               -X PATCH \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
               -H "X-GitHub-Api-Version: ${GITHUB_REST_API_VERSION}" \
               https://api.github.com/repos/${{ github.repository }}/actions/variables/OPENHORIZON_RELEASE_VERSION \
               -d "${UPDATE_SEMANTIC_VERSION_DATA}")
