Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -65,23 +65,30 @@ jobs:
       - name: Trigger Anax Release Manager
         run: |
           # Get Anax Release Environment ID
-            ANAX_RELEASE_ENVIRONMENT_ID=$( \
-              curl -L \
-                -H "Accept: application/vnd.github+json" \
-                -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
-                -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
-                'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/environments/${{ env.ANAX_RELEASE_ENVIRONMENT_NAME }}' \
-                | \
-                jq -r '.id')
+          ANAX_RELEASE_ENVIRONMENT_ID=$( \
+            curl -L \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+              'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/environments/${{ env.ANAX_RELEASE_ENVIRONMENT_NAME }}' \
+              | \
+              jq -r '.id')
 
           # Trigger Anax Release Manager
-          curl -L \
-            -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
-            -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
-            'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/workflows/${{ env.ANAX_RELEASE_MANAGER_FILE_NAME }}/dispatches' \
-            -d '{"ref":"dev-release-mgmt","inputs":{"AGBOT_VERSION": "${{ env.AGBOT_VERSION }}","ANAX_VERSION": "${{ env.ANAX_VERSION }}","ANAX_K8S_VERSION": "${{ env.ANAX_K8S_VERSION }}","ANAX_CSS_VERSION": "${{ env.ANAX_CSS_VERSION }}","ANAX_ESS_VERSION": "${{ env.ANAX_ESS_VERSION }}"}}'
+          STATUS_CHECK_ONE=$( \
+            curl -L \
+              -w "%{http_code}\\n" \
+              -X POST \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+              'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/workflows/${{ env.ANAX_RELEASE_MANAGER_FILE_NAME }}/dispatches' \
+              -d '{"ref":"dev-release-mgmt","inputs":{"AGBOT_VERSION": "${{ env.AGBOT_VERSION }}","ANAX_VERSION": "${{ env.ANAX_VERSION }}","ANAX_K8S_VERSION": "${{ env.ANAX_K8S_VERSION }}","ANAX_CSS_VERSION": "${{ env.ANAX_CSS_VERSION }}","ANAX_ESS_VERSION": "${{ env.ANAX_ESS_VERSION }}"}}')
+
+          if [[ "${STATUS_CHECK_ONE}" != *"204"* ]]; then
+            echo "::error::Anax workflow dispatch API call returned bad status code"
+            exit 1
+          fi
 
           sleep 30
 
@@ -100,13 +107,20 @@ jobs:
           # Approve workflow run automatically as this workflow run was approved
           ACCEPT_ANAX_RELEASE_API_CALL_DATA=$(jq -c -n '{"environment_ids":[$ARGS.positional[]],"state":"approved","comment":"Triggered automatically via approval from open-horizon/release"}' --jsonargs $ANAX_RELEASE_ENVIRONMENT_ID)
 
-          curl -L \
-            -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
-            -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
-            "https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs/${ANAX_RELEASE_RUN_ID}/pending_deployments" \
-            -d "${ACCEPT_ANAX_RELEASE_API_CALL_DATA}"
+          STATUS_CHECK_TWO=$( \
+            curl -L \
+              -w "%{http_code}\\n" \
+              -X POST \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${OPENHORIZON_ORGANIZATION_RELEASE_TOKEN}" \
+              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+              "https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs/${ANAX_RELEASE_RUN_ID}/pending_deployments" \
+              -d "${ACCEPT_ANAX_RELEASE_API_CALL_DATA}")
+          
+          if [[ "${STATUS_CHECK_ONE}" != *"200"* ]]; then
+            echo "::error::Anax approve workflow dispatch API call returned bad status code"
+            exit 1
+          fi
 
           sleep 30
 
@@ -128,7 +142,7 @@ jobs:
             sleep 360 #Release manager typically takes around 5.5 minutes
             check_status
             max_iterations=$((max_iterations-1))
-            if [[ "$max_iterations" -le "5" ]]; then
+            if [[ "$max_iterations" -le "0" ]]; then
               echo "::error::Anax Release Manager seems to be stuck, status won't hit completion"
               exit 1
             fi
