Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -134,163 +134,163 @@ jobs:
           OPENHORIZON_RELEASE_VERSION: ${{ vars.OPENHORIZON_RELEASE_VERSION }}
 
       # Trigger the Anax Release Manager Workflow (release.yml) to generate the Anax Release
-      - name: Trigger Anax Release Manager
-        run: |
-          # Check if Anax Release Already Exists
-          echo "::group::Check if Anax Release Already Exists via API"
-          RELEASE_STATUS=$(
-            curl -L \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
-              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
-              'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/releases/tags/v${{ env.AGBOT_VERSION }}' \
-              | jq -r '.html_url')
+      # - name: Trigger Anax Release Manager
+      #   run: |
+      #     # Check if Anax Release Already Exists
+      #     echo "::group::Check if Anax Release Already Exists via API"
+      #     RELEASE_STATUS=$(
+      #       curl -L \
+      #         -H "Accept: application/vnd.github+json" \
+      #         -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
+      #         -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+      #         'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/releases/tags/v${{ env.AGBOT_VERSION }}' \
+      #         | jq -r '.html_url')
           
-          sleep 10
+      #     sleep 10
 
-          if [[ $RELEASE_STATUS != 'null' ]]; then
-            echo "::warning title=Anax Release v${{ env.AGBOT_VERSION }} Exists::Attempted to create a release for a version of Anax that already has a release page, see $RELEASE_STATUS"
-            echo "::notice::Release process will continue without triggering a new Anax release, existing release will be linked to this Open Horizion version"
-            exit 0
-          fi
-          echo "::endgroup::"
+      #     if [[ $RELEASE_STATUS != 'null' ]]; then
+      #       echo "::warning title=Anax Release v${{ env.AGBOT_VERSION }} Exists::Attempted to create a release for a version of Anax that already has a release page, see $RELEASE_STATUS"
+      #       echo "::notice::Release process will continue without triggering a new Anax release, existing release will be linked to this Open Horizion version"
+      #       exit 0
+      #     fi
+      #     echo "::endgroup::"
 
-          sleep 10
+      #     sleep 10
 
-          # Get Anax Release Environment ID
-          echo "::group::Get Anax Release Environment ID via API"
-          ANAX_RELEASE_ENVIRONMENT_ID=$( \
-            curl -L \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
-              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
-              'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/environments/${{ env.ANAX_RELEASE_ENVIRONMENT_NAME }}' \
-              | \
-              jq -r '.id')
+      #     # Get Anax Release Environment ID
+      #     echo "::group::Get Anax Release Environment ID via API"
+      #     ANAX_RELEASE_ENVIRONMENT_ID=$( \
+      #       curl -L \
+      #         -H "Accept: application/vnd.github+json" \
+      #         -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
+      #         -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+      #         'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/environments/${{ env.ANAX_RELEASE_ENVIRONMENT_NAME }}' \
+      #         | \
+      #         jq -r '.id')
       
-          if [[ -z "$ANAX_RELEASE_ENVIRONMENT_ID" ]]; then
-            echo "::error title=Failed API Call::Failed to get Anax Release Environment ID, check API Call"
-            exit 1
-          fi
-          echo "::endgroup::"
+      #     if [[ -z "$ANAX_RELEASE_ENVIRONMENT_ID" ]]; then
+      #       echo "::error title=Failed API Call::Failed to get Anax Release Environment ID, check API Call"
+      #       exit 1
+      #     fi
+      #     echo "::endgroup::"
       
-          # Trigger Anax Release Manager
-          echo "::group::Trigger Anax Release Manager via API"
-          STATUS_CHECK_ONE=$( \
-            curl -L \
-              -w "%{http_code}\\n" \
-              -X POST \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
-              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
-              'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/workflows/${{ env.ANAX_RELEASE_MANAGER_FILE_NAME }}/dispatches' \
-              -d '{"ref":"${{ env.ANAX_RELEASE_MANAGER_BRANCH }}","inputs":{"AGBOT_VERSION": "${{ env.AGBOT_VERSION }}","ANAX_VERSION": "${{ env.ANAX_VERSION }}","ANAX_K8S_VERSION": "${{ env.ANAX_K8S_VERSION }}","ANAX_CSS_VERSION": "${{ env.ANAX_CSS_VERSION }}","ANAX_ESS_VERSION": "${{ env.ANAX_ESS_VERSION }}","IS_LATEST": "${{ env.IS_LATEST }}"}}')
+      #     # Trigger Anax Release Manager
+      #     echo "::group::Trigger Anax Release Manager via API"
+      #     STATUS_CHECK_ONE=$( \
+      #       curl -L \
+      #         -w "%{http_code}\\n" \
+      #         -X POST \
+      #         -H "Accept: application/vnd.github+json" \
+      #         -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
+      #         -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+      #         'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/workflows/${{ env.ANAX_RELEASE_MANAGER_FILE_NAME }}/dispatches' \
+      #         -d '{"ref":"${{ env.ANAX_RELEASE_MANAGER_BRANCH }}","inputs":{"AGBOT_VERSION": "${{ env.AGBOT_VERSION }}","ANAX_VERSION": "${{ env.ANAX_VERSION }}","ANAX_K8S_VERSION": "${{ env.ANAX_K8S_VERSION }}","ANAX_CSS_VERSION": "${{ env.ANAX_CSS_VERSION }}","ANAX_ESS_VERSION": "${{ env.ANAX_ESS_VERSION }}","IS_LATEST": "${{ env.IS_LATEST }}"}}')
 
-          if [[ "${STATUS_CHECK_ONE}" != *"204"* ]]; then
-            echo "::error title=Failed API Call::Anax workflow dispatch API call returned bad status code"
-            echo -e "Status:\n${STATUS_CHECK_ONE}"
-            exit 1
-          fi
-          echo "::endgroup::"
+      #     if [[ "${STATUS_CHECK_ONE}" != *"204"* ]]; then
+      #       echo "::error title=Failed API Call::Anax workflow dispatch API call returned bad status code"
+      #       echo -e "Status:\n${STATUS_CHECK_ONE}"
+      #       exit 1
+      #     fi
+      #     echo "::endgroup::"
 
-          sleep 30
+      #     sleep 30
 
-          # List most recent triggered workflows that are waiting for a deployment review, use jq to filter down to release runs created today
-          echo "::group::Get Anax Release Run ID via API"
-          ANAX_RELEASE_RUN_ID=$( \
-            curl -L \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
-              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
-              'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs?status=waiting&event=workflow_dispatch&per_page=10&page=1' \
-              | \
-              jq -r '[.workflow_runs[] | select( .path == ".github/workflows/${{ env.ANAX_RELEASE_MANAGER_FILE_NAME }}" )][0].id')
+      #     # List most recent triggered workflows that are waiting for a deployment review, use jq to filter down to release runs created today
+      #     echo "::group::Get Anax Release Run ID via API"
+      #     ANAX_RELEASE_RUN_ID=$( \
+      #       curl -L \
+      #         -H "Accept: application/vnd.github+json" \
+      #         -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
+      #         -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+      #         'https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs?status=waiting&event=workflow_dispatch&per_page=10&page=1' \
+      #         | \
+      #         jq -r '[.workflow_runs[] | select( .path == ".github/workflows/${{ env.ANAX_RELEASE_MANAGER_FILE_NAME }}" )][0].id')
 
-          if [[ -z "$ANAX_RELEASE_RUN_ID" ]]; then
-            echo "::error title=Failed API Call::Failed to get Anax Release Run ID, check API Call"
-            exit 1
-          fi
-          echo "::endgroup::"
+      #     if [[ -z "$ANAX_RELEASE_RUN_ID" ]]; then
+      #       echo "::error title=Failed API Call::Failed to get Anax Release Run ID, check API Call"
+      #       exit 1
+      #     fi
+      #     echo "::endgroup::"
 
-          sleep 30
+      #     sleep 30
 
-          # Approve workflow run automatically as this workflow run was approved
-          echo "::group::Approve Anax Release Workflow Dispatch via API"
-          ACCEPT_ANAX_RELEASE_API_CALL_DATA=$(jq -c -n '{"environment_ids":[$ARGS.positional[]],"state":"approved","comment":"Triggered automatically via approval from open-horizon/release"}' --jsonargs $ANAX_RELEASE_ENVIRONMENT_ID)
+      #     # Approve workflow run automatically as this workflow run was approved
+      #     echo "::group::Approve Anax Release Workflow Dispatch via API"
+      #     ACCEPT_ANAX_RELEASE_API_CALL_DATA=$(jq -c -n '{"environment_ids":[$ARGS.positional[]],"state":"approved","comment":"Triggered automatically via approval from open-horizon/release"}' --jsonargs $ANAX_RELEASE_ENVIRONMENT_ID)
 
-          STATUS_CHECK_TWO=$( \
-            curl -L \
-              -w "%{http_code}\\n" \
-              -X POST \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
-              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
-              "https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs/${ANAX_RELEASE_RUN_ID}/pending_deployments" \
-              -d "${ACCEPT_ANAX_RELEASE_API_CALL_DATA}")
+      #     STATUS_CHECK_TWO=$( \
+      #       curl -L \
+      #         -w "%{http_code}\\n" \
+      #         -X POST \
+      #         -H "Accept: application/vnd.github+json" \
+      #         -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}" \
+      #         -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+      #         "https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs/${ANAX_RELEASE_RUN_ID}/pending_deployments" \
+      #         -d "${ACCEPT_ANAX_RELEASE_API_CALL_DATA}")
           
-          if [[ "${STATUS_CHECK_TWO}" != *"200"* ]]; then
-            echo "::error title=Failed API Call::Anax approve workflow dispatch API call returned bad status code"
-            echo -e "Status:\n${STATUS_CHECK_TWO}"
-            exit 1
-          fi
-          echo "::endgroup::"
+      #     if [[ "${STATUS_CHECK_TWO}" != *"200"* ]]; then
+      #       echo "::error title=Failed API Call::Anax approve workflow dispatch API call returned bad status code"
+      #       echo -e "Status:\n${STATUS_CHECK_TWO}"
+      #       exit 1
+      #     fi
+      #     echo "::endgroup::"
 
-          sleep 30
+      #     sleep 30
 
-          # Wait until the Anax Release Manager has Complete
-          echo "::group::Check and Wait for Anax Release Manager to Complete via API"
-          check_status () {
-          ANAX_RELEASE_STATUS=$( \
-            curl -L \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}"\
-              -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
-              "https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs/${ANAX_RELEASE_RUN_ID}" \
-              | \
-              jq -r '.status')
-          }
+      #     # Wait until the Anax Release Manager has Complete
+      #     echo "::group::Check and Wait for Anax Release Manager to Complete via API"
+      #     check_status () {
+      #     ANAX_RELEASE_STATUS=$( \
+      #       curl -L \
+      #         -H "Accept: application/vnd.github+json" \
+      #         -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}"\
+      #         -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+      #         "https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs/${ANAX_RELEASE_RUN_ID}" \
+      #         | \
+      #         jq -r '.status')
+      #     }
 
-          max_iterations=5
-          check_status
-          while [[ "${ANAX_RELEASE_STATUS}" != "completed" ]]; do
-            sleep 360 #Release manager typically takes around 5.5 minutes
-            check_status
-            max_iterations=$((max_iterations-1))
-            echo "Status Check Complete, Remaining Opportunities ${max_iterations}/5"
-            if [[ "$max_iterations" -le "0" ]]; then
-              echo "::error title=Anax Release Stuck::Anax Release Manager seems to be stuck, status won't hit completion"
-              exit 1
-            fi
-          done
-          echo "Status was marked completed, moving on."
-          echo "::endgroup::"
+      #     max_iterations=5
+      #     check_status
+      #     while [[ "${ANAX_RELEASE_STATUS}" != "completed" ]]; do
+      #       sleep 360 #Release manager typically takes around 5.5 minutes
+      #       check_status
+      #       max_iterations=$((max_iterations-1))
+      #       echo "Status Check Complete, Remaining Opportunities ${max_iterations}/5"
+      #       if [[ "$max_iterations" -le "0" ]]; then
+      #         echo "::error title=Anax Release Stuck::Anax Release Manager seems to be stuck, status won't hit completion"
+      #         exit 1
+      #       fi
+      #     done
+      #     echo "Status was marked completed, moving on."
+      #     echo "::endgroup::"
 
-          sleep 30
+      #     sleep 30
 
-          # Confirm that the workflow in the Anax repo ran successfully
-          echo "::group::Get Success Status of Anax Release Workflow via API"
-          ANAX_RELEASE_CONCLUSION=$( \
-              curl -L \
-                -H "Accept: application/vnd.github+json" \
-                -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}"\
-                -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
-                "https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs/${ANAX_RELEASE_RUN_ID}" \
-                | \
-                jq -r '.conclusion')
+      #     # Confirm that the workflow in the Anax repo ran successfully
+      #     echo "::group::Get Success Status of Anax Release Workflow via API"
+      #     ANAX_RELEASE_CONCLUSION=$( \
+      #         curl -L \
+      #           -H "Accept: application/vnd.github+json" \
+      #           -H "Authorization: Bearer ${OPENHORIZON_RELEASE_MANAGER_TOKEN}"\
+      #           -H "X-GitHub-Api-Version: ${{ env.GITHUB_REST_API_VERSION }}" \
+      #           "https://api.github.com/repos/${{ env.ANAX_REPOSITORY_OWNER }}/${{ env.ANAX_REPOSITORY_NAME }}/actions/runs/${ANAX_RELEASE_RUN_ID}" \
+      #           | \
+      #           jq -r '.conclusion')
           
-          if [[ "${ANAX_RELEASE_CONCLUSION}" != "success" ]]; then
-              echo "::error title=Anax Release Failed::Anax Release Manager appears to have failed, been cancelled, or the API call failed"
-              exit 1
-          fi
-          echo "::endgroup::"
-        shell: bash
-        env:
-          AGBOT_VERSION: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_agbot }}
-          ANAX_VERSION: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_anax }}
-          ANAX_K8S_VERSION: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_anax_k8s }}
-          ANAX_CSS_VERSION: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_cloud-sync-service }}
-          ANAX_ESS_VERSION: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_edge-sync-service }}
-          IS_LATEST: ${{ github.event.inputs.IS_LATEST }}
+      #     if [[ "${ANAX_RELEASE_CONCLUSION}" != "success" ]]; then
+      #         echo "::error title=Anax Release Failed::Anax Release Manager appears to have failed, been cancelled, or the API call failed"
+      #         exit 1
+      #     fi
+      #     echo "::endgroup::"
+      #   shell: bash
+      #   env:
+      #     AGBOT_VERSION: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_agbot }}
+      #     ANAX_VERSION: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_anax }}
+      #     ANAX_K8S_VERSION: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_anax_k8s }}
+      #     ANAX_CSS_VERSION: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_cloud-sync-service }}
+      #     ANAX_ESS_VERSION: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_edge-sync-service }}
+      #     IS_LATEST: ${{ github.event.inputs.IS_LATEST }}
 
       # Trigger the Examples Release Manager Workflow (release.yml) to generate the Examples Release
       - name: Trigger Examples Release Manager
@@ -450,18 +450,7 @@ jobs:
       - name: Create Open Horizon Release
         run: |
           cd $RUNNER_TEMP
-          printf "Open Horizon Components
-          Anax:
-            Agbot: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_agbot }}
-            Anax: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_anax }}
-            Anax K8s: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_anax_k8s }}
-            Cloud Sync Service (CSS): ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_cloud-sync-service }}
-            Edge Sync Service (ESS): ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_edge-sync-service }}
-          Exchange API: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_exchange-api }}
-          Vault: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).amd64_vault }}
-          FDO: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).fdo-owner-services }}
-          SDO: ${{ fromJSON(github.event.inputs.VERSION_JSON_FILE).sdo-owner-services }}
-          " > Released_Versions.txt
+          printf "${{ github.event.inputs.VERSION_JSON_FILE }}" > Released_Versions.txt
 
           printf "### Open Horizon ${{ steps.update_version.outputs.NEW_RELEASE }} Release Information
           
